node { /* This is a scripted pipeline */
    def app /* define a variable */

    stage ('Clone repository') {
        /* clone the repo into the workspace */
        /* scm is a special variable which instructs the checkout step to clone the specific repo. */
        checkout scm
    }

    stage ('Build image') {
        /* build the docker image */
        app = docker.build("nginx-server", "nginx-web-server")
    }

    stage ('Test image') {
        echo "Tests passed"
        bat 'echo %PATH%'
    }
}